
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-clsutar-ai-v1-selfcrdv2
  failurePolicy: Fail
  name: selfcrdv2.core.clustar.ai
  rules:
  - apiGroups:
    - core.clustar.ai
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - selfcrdv2s
